spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: helloworld
    url: jdbc:mysql://localhost:3306/demo-api

  jpa:
    hibernate:
      ddl-auto: update
